version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python run.py
    ports:
      - 5000:5000
    environment:
      - DB_USER=root
      - DB_PASS=Admin@123
      - DB_HOST=db
      - DB_NAME=law-db
      - DOCKER_ENV=1
      - HOST=0.0.0.0
      - CLOUDINARY_CLOUD_NAME=dljmwib1r
      - CLOUDINARY_API_KEY=551239148838771
      - CLOUDINARY_API_SECRET=FCXYKNM3fQHa9ein5j-WJB90H0s
      - CORS_URL=https://infinithree.netlify.app
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=law-db
    volumes:
      - law-db-data:/var/lib/mysql

volumes:
  law-db-data: