version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_USER=root
      - DB_PASS=Admin@123
      - DB_HOST=localhost
      - DB_NAME=law-db

    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=law-db
