version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python run.py
    ports:
      - 5050:5000
    environment:
      - DB_USER=root
      - DB_PASS=Admin@123
      - DB_HOST=db
      - DB_NAME=law-db
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=law-db
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
